DROP TABLE NUMAPPARTIENTA;
DROP TABLE PARTICIPEA;
DROP TABLE PSEUDODE;
DROP TABLE ESTSPE;
DROP TABLE EVALUATIONS;
DROP TABLE NUMEROS;
DROP TABLE SPECTACLES;
DROP TABLE SPECIALITES;
DROP TABLE ARTISTES;

COMMIT;
