CREATE TABLE ARTISTES
        (IDARTISTE INTEGER,
        NOM VARCHAR(255),
        PRENOM VARCHAR(255),
        NAISSANCE DATE not NULL,
        CIRQUE VARCHAR(255),
        TEL VARCHAR(10),
        PRIMARY KEY (IDARTISTE));

CREATE TABLE SPECIALITES
	(NOMSPE VARCHAR(255),
	PRIMARY KEY(NOMSPE));

CREATE TABLE SPECTACLES
        (IDSPECTACLE INTEGER,
        THEME VARCHAR(255),
        JOUR INTEGER CHECK(JOUR > 0 AND JOUR < 5) ,
        HEURE INTEGER CHECK(HEURE = 9 OR HEURE = 14),
        PRIX INTEGER NOT NULL,
        IDPRESENTATEUR INTEGER not NULL,
        PRIMARY KEY (IDSpectacle),
        FOREIGN KEY(IDPRESENTATEUR) REFERENCES ARTISTES(IDARTISTE),
	FOREIGN KEY(THEME) REFERENCES SPECIALITES(NOMSPE));

CREATE TABLE NUMEROS
        (IDNUM INTEGER,
        TITRE VARCHAR(255),
        THEME VARCHAR(255),
        RESUME VARCHAR(255),
        DUREE INTEGER NOT NULL CHECK (DUREE > 9 AND DUREE < 31),
        CIRQUE VARCHAR(255),
        IDARTISTEPRINCIPAL INTEGER not NULL,
        PRIMARY KEY (IDNUM),
        FOREIGN KEY(IDARTISTEPRINCIPAL) REFERENCES ARTISTES(IDARTISTE),
	FOREIGN KEY(THEME) REFERENCES SPECIALITES(NOMSPE));

CREATE TABLE EVALUATIONS
	    (IDEXPERT INTEGER not NULL,
	    IDNUM INTEGER not NULL,
	    NOTE INTEGER NOT NULL CHECK (Note < 11),
	    COMMENTAIRE VARCHAR(255),
	    PRIMARY KEY(IDExpert,IDNUM),
	    FOREIGN KEY(IDNUM) REFERENCES NUMEROS(IDNUM),
	    FOREIGN KEY(IDEXPERT) REFERENCES ARTISTES(IDARTISTE));

CREATE TABLE ESTSPE
	(IDARTISTE INTEGER not NULL,
  NOMSPE VARCHAR(255) not NULL,
  PRIMARY KEY(IDARTISTE, NOMSPE),
	FOREIGN KEY(IDARTISTE) REFERENCES ARTISTES(IDARTISTE),
	FOREIGN KEY(NOMSPE) REFERENCES SPECIALITES(NOMSPE));

CREATE TABLE PSEUDODE
	    (IDARTISTE INTEGER not NULL,
	    PSEUDO VARCHAR(255),
	    PRIMARY KEY(IDARTISTE, PSEUDO),
	    FOREIGN KEY(IDARTISTE) REFERENCES ARTISTES(IDARTISTE));

CREATE TABLE PARTICIPEA
            (IDARTISTE INTEGER not NULL,
            IDNUM INTEGER not NULL,
            PRIMARY KEY(IDARTISTE, IDNUM),
            FOREIGN KEY(IDARTISTE) REFERENCES ARTISTES(IDARTISTE),
            FOREIGN KEY(IDNUM) REFERENCES NUMEROS(IDNUM));

CREATE TABLE NUMAPPARTIENTA
            (IDSPECTACLE INTEGER not NULL,
	    IDNUM INTEGER not NULL,
            PRIMARY KEY(IDSPECTACLE, IDNUM),
            FOREIGN KEY(IDSPECTACLE) REFERENCES SPECTACLES(IDSPECTACLE),
	    FOREIGN KEY(IDNUM) REFERENCES NUMEROS(IDNUM));


COMMIT;
